//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModbusPart.Properties.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModbusPart.Properties.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 增加设备 的本地化字符串。
        /// </summary>
        public static string Add_Device {
            get {
                return ResourceManager.GetString("Add Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加COM 的本地化字符串。
        /// </summary>
        public static string AddCOM {
            get {
                return ResourceManager.GetString("AddCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加TCP/IP 的本地化字符串。
        /// </summary>
        public static string AddTCP {
            get {
                return ResourceManager.GetString("AddTCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波特率 的本地化字符串。
        /// </summary>
        public static string Baudrate {
            get {
                return ResourceManager.GetString("Baudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯槽(COM) 的本地化字符串。
        /// </summary>
        public static string COM {
            get {
                return ResourceManager.GetString("COM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COM通讯槽数量 的本地化字符串。
        /// </summary>
        public static string COM_Port_Amount {
            get {
                return ResourceManager.GetString("COM Port Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明 的本地化字符串。
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资料位元 的本地化字符串。
        /// </summary>
        public static string Data_Bit {
            get {
                return ResourceManager.GetString("Data Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除该通道 的本地化字符串。
        /// </summary>
        public static string Delete_this_Port {
            get {
                return ResourceManager.GetString("Delete this Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除此设备 的本地化字符串。
        /// </summary>
        public static string Deletethisdevice {
            get {
                return ResourceManager.GetString("Deletethisdevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除当前行数据？ 的本地化字符串。
        /// </summary>
        public static string Deletethisline {
            get {
                return ResourceManager.GetString("Deletethisline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连线设备数量 的本地化字符串。
        /// </summary>
        public static string Device_Amount {
            get {
                return ResourceManager.GetString("Device Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 致能 的本地化字符串。
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误暂存器 的本地化字符串。
        /// </summary>
        public static string ErrorRegister {
            get {
                return ResourceManager.GetString("ErrorRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能码 的本地化字符串。
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯线名称 的本地化字符串。
        /// </summary>
        public static string GatewayName {
            get {
                return ResourceManager.GetString("GatewayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IMP本机从站站号 的本地化字符串。
        /// </summary>
        public static string IMP_Slave_Station {
            get {
                return ResourceManager.GetString("IMP Slave Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址 的本地化字符串。
        /// </summary>
        public static string IP_Address {
            get {
                return ResourceManager.GetString("IP Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置IP地址 的本地化字符串。
        /// </summary>
        public static string IPisNull {
            get {
                return ResourceManager.GetString("IPisNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M 地址 的本地化字符串。
        /// </summary>
        public static string MAddress {
            get {
                return ResourceManager.GetString("MAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modbus 设置 的本地化字符串。
        /// </summary>
        public static string ModbusSetting {
            get {
                return ResourceManager.GetString("ModbusSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M 暂存器 的本地化字符串。
        /// </summary>
        public static string MRegister {
            get {
                return ResourceManager.GetString("MRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前输入文本为非法IP地址 的本地化字符串。
        /// </summary>
        public static string NotCorrectIP {
            get {
                return ResourceManager.GetString("NotCorrectIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 奇偶 的本地化字符串。
        /// </summary>
        public static string Parity {
            get {
                return ResourceManager.GetString("Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯槽 的本地化字符串。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯格式 的本地化字符串。
        /// </summary>
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 范围:0~255 的本地化字符串。
        /// </summary>
        public static string Range_0_255 {
            get {
                return ResourceManager.GetString("Range:0~255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 范围:1-65535 的本地化字符串。
        /// </summary>
        public static string Range_1_65535 {
            get {
                return ResourceManager.GetString("Range:1-65535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取最大长度 的本地化字符串。
        /// </summary>
        public static string ReadLength {
            get {
                return ResourceManager.GetString("ReadLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取记忆体配对 的本地化字符串。
        /// </summary>
        public static string ReadRegisterMapping {
            get {
                return ResourceManager.GetString("ReadRegisterMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂存器 的本地化字符串。
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重试次数 的本地化字符串。
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站号 的本地化字符串。
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止位元 的本地化字符串。
        /// </summary>
        public static string Stop_Bit {
            get {
                return ResourceManager.GetString("Stop Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯地址(16进制) 的本地化字符串。
        /// </summary>
        public static string TagAddress_Hex_ {
            get {
                return ResourceManager.GetString("TagAddress(Hex)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯地址数量 的本地化字符串。
        /// </summary>
        public static string TagAmount {
            get {
                return ResourceManager.GetString("TagAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络通信槽 的本地化字符串。
        /// </summary>
        public static string TCP_Port {
            get {
                return ResourceManager.GetString("TCP Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络IP通讯槽数量 的本地化字符串。
        /// </summary>
        public static string TCP_Port_Amount {
            get {
                return ResourceManager.GetString("TCP Port Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时时间 的本地化字符串。
        /// </summary>
        public static string Time_Out {
            get {
                return ResourceManager.GetString("Time Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类别 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位:毫秒 的本地化字符串。
        /// </summary>
        public static string Unit_ms {
            get {
                return ResourceManager.GetString("Unit:ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新速度 的本地化字符串。
        /// </summary>
        public static string Update_Period {
            get {
                return ResourceManager.GetString("Update Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入记忆体配对 的本地化字符串。
        /// </summary>
        public static string WriteRegisterMapping {
            get {
                return ResourceManager.GetString("WriteRegisterMapping", resourceCulture);
            }
        }
    }
}
